version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance  # Persist database
      - ./uploads:/app/uploads    # Persist uploaded files
    environment:
      - FLASK_ENV=production
