apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quoteforge-db
  namespace: quoteforge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quoteforge-uploads
  namespace: quoteforge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
