name: Deploy QuoteForge

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: self-hosted  # Use your own runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy QuoteForge
      run: |
        cd ~/QuoteForge
        git pull origin master
        docker stop quoteforge-web || true
        docker rm quoteforge-web || true
        docker build -t quoteforge:latest .
        docker run -d -p 5000:5000 \
          -v $(pwd):/app \
          -v $(pwd)/instance:/app/instance \
          -v $(pwd)/uploads:/app/uploads \
          --name quoteforge-web \
          quoteforge:latest
        echo "Deployment completed successfully!"
